### ISSUE TITLE
Comparison for javascript libraries

### ISSUE THREAD

**Issue by vorabrijesh** [ualberta-smr/LibraryMetricScripts#20]
Hello, we have been extending your project as a software engineering lab. We are a team of 3 students. 

Link:
https://github.com/vorabrijesh/Selab-Librarymetric

Have a look at screenshots.pdf for the work we have done till now. We are still working on it. Soon we will add python and java libraries also and some more metrics to compare.

Any suggestion on how to improve is always welcome.

**Comment by snadi** [comment]
Hi Vora

I'm extremely sorry for the late reply. Somehow, I didn't get a notification for this and only saw it now when going through old issues. Thanks for contacting me through email earlier! Please feel free to submit PRs if you'd like to contribute your work.. It would require some re-organization of the code though. Right now, I'm working on some cleanup anyways for the current code. I'll take a look at your code to see if there might be opportunities to refactor things here to help with future extensions. For now, I'll close the issue.

Sarah
